### Get all users
http://localhost:8000/api/users

### Create a user with POST request
POST http://localhost:8000/api/users
{
    "username": "John Doe",
    "email": "john@doe.com",
    //picture link
    "picture": "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    "serviceProvider": "google"
}

### Get test token route
http://localhost:8000/api/testToken
